// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using WatchKit;

namespace xcf_watch.WatchOSApp
{
	public partial class NotificationController : WKInterfaceController
	{
		public NotificationController (IntPtr handle) : base (handle)
		{
		}
	}
}
